# menu.py

menu = {
    '🍱 Setlar': {
        'Kombo set': {'price':20000, 'image':'https://api.lesailes.uz/storage/products/2022/03/16/p0TZUFzdFp7riQd4NFukH7bYCguz0h9jT5jbHNXy.webp',
                      'description': 'Fri kartoshkasi Coca-cola 0.5 '},
        'Klassik set':{'price':34000, 'image':'https://api.lesailes.uz/storage/products/2022/09/08/h7WO4cUYGJBiBUFs2qeUAYMhe5xYEXlSSLd1LWCa.webp',
                       'description': 'Klassik burgerCoca-cola 0.3 Fri kartoshkasi S '},
        'Skul set': {'price':36000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/uJTcWJyBmtLq9abqzFXeiNgwFcItwFPGrllH9lGW.webp',
                     'description': 'Hot-dog Coca-cola 0.3 Fri kartoshkasi SKetchup sousi '},
        'Dostlar 1x':{'price': 43000, 'image':'https://api.lesailes.uz/storage/products/2022/06/15/d4xA2cZWeidDPxv0mlQ2hsYEMQacOIqsWbWy92XR.png',
                      'description': "Qanotchalar 3Tovuq sharchalari 2Tovuq nagetsi 2Kartoshka fri SKetchup "},
        'Dostlar 1x, achchiq':{'price':43000, 'image':'https://api.lesailes.uz/storage/products/2022/06/15/d4xA2cZWeidDPxv0mlQ2hsYEMQacOIqsWbWy92XR.png',
                                'description': "Achchiq qanotchalar 3Tovuq sharchalari 2Tovuq nagetsi 2Kartoshka fri SKetchup "},
        'Qiyqiriq set':{'price': 45000, 'image':'https://api.lesailes.uz/storage/products/2023/08/29/HZUU2lH1ZbPF8RUMbkI00HctLUq3UCBwisuMKesd.webp',
                        'description': "Barbekyu lesterPishloqli toviq sharchalari, 3 donaAystiJo'shqin salati "},
        'Longer rings set':{'price': 45000, 'image':'https://api.lesailes.uz/storage/products/2022/10/04/xJNb3iZ1NJ8Yx11eVSQ3X2CMSn5nruiAH8p9A35U.webp',
                            'description': "Longer ringsTovuq sharchalari 3Fri kartoshkasi SKetchup "},
        'Lester set':{'price': 53000, 'image':'https://api.lesailes.uz/storage/products/2022/03/09/9RplsrJissmFUdjyIDNnRsjr12vfFUc2RZwd7iOq.webp',
                      'description': "Lester tosterNaggetslar, 3 dona Coca-cola 0.5 Fri kartoshkasi S Ketchup sousi "},
        'Snek set':{'price': 79000, 'image':'https://api.lesailes.uz/storage/products/2023/10/12/cbidR6KU18nziNPphlU3jpa8OZi1nhaRKJkc93Cn.webp',
                    'decription': "Pishloqli tovuq sharchalari 5Chiken stiks 5Tovuq nagetsi 5Pishloqli kartoshka sharchalari 5Fri kartoshkasi LKetchup 2 "},
        'Dostlar 2x':{'price': 79000, 'image':'https://api.lesailes.uz/storage/products/2022/06/15/gUqY4V5v1yNFBfmIE5kctBhaStWhRITdUcpb6uZi.png',
                      'description': "Qanotchalar 6Tovuq sharchalari 6Chiken korn Kartoshka fri LKetchup 2 "},
        'Dostlar 2x, achchiq':{'price': 79000, 'image':'https://api.lesailes.uz/storage/products/2022/06/15/gUqY4V5v1yNFBfmIE5kctBhaStWhRITdUcpb6uZi.png',
                                'description': "Achchiq qanotchalar 6Tovuq sharchalari 6Chiken korn Kartoshka fri LKetchup 2 "},
    },

    '🍗 Tovuq': {
        'Chiken korn':{'price': 18000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/KmhdUqmEKWbGPxqGszEmP1Ib3f5UhE4xLQZm63US.webp',
                       'description': "Yumshoq tovuq bo'lakchalari "},
        'Qanot, 3 dona':{'price': 22000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/q6Zz1EDiIhMMt4cAHvKT2AbikYGhInSipE9qawmg.webp',
                         'description': "Maxsus panirovkadagi, tovuqning xushta‘m qanotlari (Halal). 3 dona "},
        'Achchiq Qanot, 3 dona':{'price': 22000, 'image':'https://api.lesailes.uz/storage/products/2022/05/06/ybcbXwjTDHdH04M44P3cxxRIVhFDh5GKajwkGbfj.png',
                                  'description': "Achchiq maxsus panirovkadagi, tovuqning xushta‘m qanotlari (Halal). 3 dona "},
        'Strips, 3 dona':{'price': 22000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/KmhdUqmEKWbGPxqGszEmP1Ib3f5UhE4xLQZm63US.webp',
                          'description': "Tovuqning maxsus panirovkadagi mayin filesi (Halal). 3 dona "},
        'Achchiq Strips, 3 dona':{'price': 22000, 'image':'https://api.lesailes.uz/storage/products/2022/05/06/uwcVinTefseVa26Q2T1nt98KITURkb6NMR9Yx92O.png',
                                   'description': "Maxsus panirovkadagi, o‘tkir ziravorli, tovuqning mayin filesi (Halal). 3 dona "},
        'Chiziz chiken korn':{'price': 38000, 'image':'https://api.lesailes.uz/storage/products/2023/02/27/YFNM3iOwoH1MOePLcvaokIXMYLfxINYevTQ0wpwP.webp',
                              'description': "Pishloq sousidagi yumshoq tovuq bo'lakchalari "},
    },

    '🍟 Sneklar': {
        'Tovuqli nagetsi, 3 dona':{'price': 14000, 'image':'https://api.lesailes.uz/storage/products/2023/01/24/jOF0andmSuQH7HByJ7TxZ00mC23TE5JC8QetB6KZ.webp',
                                    'description': "Maxsus panirovka bilan qoplangan, tovuq qiymasidan tayyorlangan ishtahaochar naggetslar "},
        'Chiken stiks, 3 dona':{'price': 14000, 'image':'https://api.lesailes.uz/storage/products/2023/01/24/QRHiz6nJ7S6ZMKS7q3MRvxr8W8btihhZdffA10OM.webp',
                                'description': "Maxsus panirovka bilan qoplangan, tovuq qiymasidan tayyorlangan ishtahaochar naggetslar (Halal) "},
        'Fri kartoshkasi':{'price': 15000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/kp8eGfzJqockuM9osFGgJRxQytAl93lgRtcFLo9d.webp',
                           'description': "Ishtahaochar, qarsildoq fri kartoshkasi. "},
        'Pishloqli kartoshka sharchasi, 7 dona':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2022/11/15/vLdLVsVy4sXPQJQKGtTkVybXkbThJVSDTq7xkdhV.webp',
                                                  'description': "Maxsus panirovkadagi, pishloqli kartoshka sharchalari. 7 dona "},
        'Pishloqli tovuq sharchasi, 3 dona':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2024/01/31/HgZsE0G1oUniJjS5gSSxCIoLwUTXa5XtB7eGvtUP.webp',
                                              'description': "Maxsus panirovkadagi, yumshoq va mazali, pishloqli tovuq sharchalari (Halol). "},
        'Jaydari kartoshka':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/VFbXTLqlOFyISDb2RkM49liUAe9GR1n3UdaPUBwP.webp',
                             'description': "Ziravorlar bilan qovurilgan, ishtahaochar kartoshka bo'laklari. "},
    },

    '🌯 Lester': {
        'Lester sezar':{'price':25000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/HVtdHyIp8meqx2Hv35J8zPbYeQjshbRnT3NqhsKk.webp',
                        'description': "Lavash, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), aysberg salati, sezar sousi "},
        'Amerikan lester':{'price':25000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/api76fbHhq2IJse17cRXst3pOzWfEgJk1cr0N2vM.webp',
                            'description': "Lavash, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), qovurilgan kartoshka, tuzlangan bodring, piyoz, mayonez va ketchup sousi. "},
        'Lester Toster':{'price': 25000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/1inRF2uRFvw1ATnug0CcYewea8aaDxw3GaAzPVlR.webp',
                         'description': "Lavash xamiri, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), sarxil pomidor, tuzlangan bodring, salat bargi, mayonez va ketchup sousi. "},
        'Barbekyu lester':{'price': 25000, 'image':'https://api.lesailes.uz/storage/products/2022/04/25/vwKig6jct1DLOwuyUujZUKth6HSL3YlDMwO85rDT.png',
                           'description': "Lavash, maxsus panirovkali yumshoq tovuq filesi (Halol), sarxil pomidor va bodring, salat bargi, mayonez va ishtahaochar BBQ sousi "},
        'Lester Chili':{'price': 26000, 'image':'https://api.lesailes.uz/storage/products/2022/10/18/TJdmKPrnhC1vp2EDod8WFpitBvmebDJq2R674P2y.webp',
                        'description': "Lavash xamiri, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), sarxil pomidor, tuzlangan bodring, salat bargi, mayonez va chili sousi "},
        'Lester xalapeno':{'price': 27000, 'image':'https://api.lesailes.uz/storage/products/2022/10/18/AlJB2s4xQTYZt9p1uCJq38pDhtmFHkKMP7zcqlcl.webp',
                           'description': "Lavash xamiri, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), sarxil pomidor, salat bargi, xalapenyo qalampiri, mayonez va ketchup sousi. "},
        'Big boks': {'price':31000,'image':'https://api.lesailes.uz/storage/products/2022/02/16/ktJIGPN7f6EOoEhEaHdOIW1QRG5ynEhs8W2euf3a.webp',
                     'description': "Lavash, maxsus panirovka bilan qoplangan yumshoq tovuq filesi (Halol), kartoshka pyuresi, Chedder pishlog'i, sarxil pomidor bo'laklari, salat bargi, mayonez sousi. "},
    },

    '🍔 Burgerlar': {
        'klassic':{'price': 23000, 'image':'https://api.lesailes.uz/storage/products/2022/04/25/S0O61PZTefWH1w13BSArFUsGGiDqgm3wDIOd1mWW.png',
                   'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mayin tovuq filesi (Halol), pomidor bo'laklari, tuzlangan bodring, salat bargi, mayonez va ketchup sousi "},
        'Cesar':{'price': 25000,
                 'image':'https://api.lesailes.uz/storage/products/2022/02/23/ZtbevHISVM690STmbgWNWqF0TQDi3Y4IF2tuOF7i.webp',
                 'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan sarxil tovuq kotleti (Halol), sarxil pomidor bo'laklari, aysberg salati, sezar sousi."},
        'Singer':{'price': 25000, 'image':'https://api.lesailes.uz/storage/products/2022/10/18/sQSJcoIUMOsvBLwOOG4dSKxd7bC5XMTYZ0ehn8Ml.webp',
                  'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mayin tovuq filesi (Halol), pomidor bo'laklari, tuzlangan bodring, salat bargi, mayonez va chili sousi "},
        'Barbekyu burger':{'price': 25000,'image':'https://api.lesailes.uz/storage/products/2022/04/25/S0O61PZTefWH1w13BSArFUsGGiDqgm3wDIOd1mWW.png',
                            'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mazali tovuq kotleti (Halol), pomidor bo'laklari, aysberg salati, mayonez sousi va ishtahaochar barbekyu sousi "},
        'Chiken chiz':{'price':25000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/2wAZOqWIyajn3IJGjqmVjvlODqMfWnLhmecJY2ru.webp',
                       'description':"Yumshoq bulochka, sarxil tovuq kotleti (Halol), Chedder pishlog'i, sarxil pomidor bo'laklari, aysberg salati, mayonez va ketchup sousi. "},
        'Xalapenyo burger':{'price': 26000, 'image':'https://api.lesailes.uz/storage/products/2022/10/18/142uHGuYKiJogZqsuofbSobB5HylR2Dw11ljgp3E.webp',
                            'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mayin tovuq filesi (Halol), pomidor bo'laklari, tuzlangan bodring, salat bargi, xalapenyo qalampiri, mayonez va ketchup sousi "},
        'Biger':{'price': 28000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/pOFudHsA8LfVZldlFcgOUSXiXrrbkeSwMQLi5tPQ.webp',
                 'description':"Yumshoq bulochka, dudlangan mol go'shti (Halol), maxsus panirovka bilan qoplangan mayin tovuq filesi (Halol), Chedder pishlog'i, pomidor bo'laklari, tuzlangan bodring, salat bargi, mayonez va ketchup souslari "},
        'Dabl chiken chiz':{'price': 32000, 'image':'https://api.lesailes.uz/storage/products/2022/04/25/sJsfijBgVVVtyo3Cv7kjWyp737OA2cLES7Rv0OoA.png',
                            'description':"Yumshoqqina bulochka,ikkita shirador tovuq kotleti (Halal), chedder pishlog‘i, yangi pomidor, marinadlangan bodiring, aysberg salat barglari, mayonez va ketchup souslari "},
    },

    '🌭 Longerlar/Hot-dog': {
        'Hot-dog':{'price': 20000, 'image':'https://api.lesailes.uz/storage/products/2022/02/13/4Km4MAaGKBYnwUkggmKEyKRP6BX6zagH9yBcQkpH.jpg',
                   'description':"Mini longer bulochka, Yegerskiye sosiskasi (Halol), tuzlangan bodring, xantal, mayonez va ketchup souslari "},
        'Longer':{'price': 21000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/VLLtj0AlH6GUcRPwkv0ipoMEFFOLbnZ5iSBxqzwi.webp',
                  'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mayin tovuq filesi (Halol), pomidor bo'laklari, salat bargi, mayonez va ketchup souslari "},
        'Longer rings':{'price': 22000, 'image':'https://api.lesailes.uz/storage/products/2022/09/16/Wk3t8tZXrl6UCQriUzFiDYXtCuUl7a44fNvDZ2wC.webp',
                        'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mayin aylanalari filesi (Halol), pomidor bo'laklari, tuzlangan bodring, salat bargi, mayonez va ketchup souslari "},
        'Longer chiz':{'price': 23000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/T7f64oIKfV0jPmysFtWiGmVJE5jXYjHVUQDhrUjx.webp',
                       'description':"Yumshoq bulochka, maxsus panirovka bilan qoplangan mazali tovuq filesi (Halol), Chedder pishlog'i, pomidor bo'laklari, salat bargi, mayonez va ketchup souslari "},
    },

    '🥤 Ichimliklar': {
        'Montella 0.33':{'price': 3000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/5bUWR6yQcwTFkQr2CPYjuaVQSLhNYvta5ZqMTbhp.webp'},
        'Qora choy': {'price': 5000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/3WxJGzmtI3idFAoY7WbtyKP1MC5duuRqD4xeupc7.webp'},
        'Kok choy':{'price': 5000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/CCprmf6bGurf40KRDcyU7eTkIKgHRSC7nG77NF8Z.webp'},
        'Limon choy(qora)':{'price': 6000, 'image':'https://api.lesailes.uz/storage/products/2022/02/23/xA2gj6IFzIesaUxyQYbUwKDlfF7JSofe2T1YJ1F1.webp'},
        'Limon choy(kok)':{'price': 6000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/EToenxCF19QX3hnQytjo74pDHoDvVwhSvN2apy1H.webp'},
        'Coca-cola 0.5':{'price': 9000, 'image':'https://api.lesailes.uz/storage/products/2022/03/10/UyfI6iXfLomwRz6asNfo54WFASUWo5rZK6Qt8vbE.webp'},
        'Fanta 0.5':{'price': 9000, 'image':'https://api.lesailes.uz/storage/products/2022/03/10/7ZqBtLuamHL6B1kQs5ox5eFdBE2jSMgrGPVi04Mz.webp'},
        'Ice Tea':{'price': 17000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/dyVu9r5bOCAgmejJsuhFdX8xLd0fQiEegIyMN5AA.webp',
                   'description':"Meva bo'laklari solingan tetiklashtiruvchi salqin choy. "},
        'Coffee':{'price': 5000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/6n24c42FnTE34WLoDbZpENYO9O6ebm8DpEJVJzmS.webp'},
        'Les tea':{'price': 12000, 'image':'https://api.lesailes.uz/storage/products/2023/11/29/Xqdv326vVI8CVhk1SSLEH5Wp7OtAnUZrqHja8en1.webp',
                   'description':"Apelsin va yalpiz bilan damlangan shakarli, qaynoq karkade choy "},
    },

    '🥗 Salatlar': {
        'Koulslou':{'price': 10000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/p6IJKHtlsTlVBZx4s9vnd3MGz5ls4PK0c0QAjzMY.webp',
                    'description':"Oq karam, qizil sabzi, sirka, shakar va mayonez sousi. "},
        'Sezam':{'price': 25000, 'image':'https://api.lesailes.uz/storage/products/2022/04/25/pSWNI5akbeZxs54cIGRty5FdXHIe0JKK9j0r5drv.png',
                 'description':"Aysberg salati va yumshoqqina tovuq bo'lakchalari (Halol) solingan, kunjut urug'i sepilgan, ishtahaochar teriyaki sousidagi shirali salat. "},
        'Les Barbekyu':{'price': 30000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/ofEtcxB13VYx1GRjrctDYXQcikk4Am7HaQy0UDFI.webp',
                        'description':"BBQ tovuq bo'lakchalari, ananas, aysberg salati, bodiring, rukkola va ishtahaochar teriyaki sousi "},
        'Grechka':{'price':30000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/YtZ4Od790EWmHl0bd5nBeFsQvEmPjwP2tDmVJYz5.webp0',
                   'description':"Limon va rayhon sousli, salat barglari, pomidor, zaytun, bodring va fetaks pishloqli sarxil salat. "},
        'Sezar':{'price': 30000, 'image':'https://api.lesailes.uz/storage/products/2022/09/19/uDJaK36xcThumQcVYsB96QWfzxkD7b4vZ98VaTuC.webp',
                 'description':"Tovuq filesi (Halol), parmesan pishlog'i, cherri pomidori, suxari, aysberg salati, sezar sousi "},
    },

    '🍩 Donats': {
        'Blueberry donut':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/jj1RAjLupZc2pZdYjkCK8371y5Qz5lQ3VKrdGetU.png'},
        'Caramel':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/4bfUNkEGnPX1IXwinKGqsqCZgFqpawRenQZJwoyo.png'},
        'Cinnamon':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/OsDy8idoPQUK7zcguwUlTl3aCKX3XacPM8BIbRaO.png'},
        'Cookies':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/KLKDAI3x3VClMPBVEGP0aluFkQpRP7quledHGcn7.png'},
        'Nutty cream':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/fQzl0g260oG52hp5z0oBhZtYY9obfU7hXTYGYntU.png'},
        'Panna cotta':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/YO9OUWy3NtbE8v3RF9f7drl3T5mCY6S6Spwe4QD1.png'},
        'Strawberry':{'price': 16000, 'image':'https://api.lesailes.uz/storage/products/2023/04/14/iALxA7L1VywGHBPyIv33W81cQYo8PZFxY8jfQbVP.png'}
    },

    '🍅 Souslar': {
        'Ketchup':{'price': 3000, 'image':'https://api.lesailes.uz/storage/products/2023/11/02/rDBrPGwFET7ang8QoYYt7MdH8FWT3AafTLjZUbMJ.webp'},
        'Chili':{'price': 4000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/dzSXPK6XomRcUf1Zdh1xPjXD5kf1sevoRbpibqVS.webp'},
        'Sezar':{'price': 4000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/XkkH9IG3jTyW3VgLBHjmEYKrxvkCeJsmGgbb4c3D.webp'},
        'Mayonez':{'price': 4000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/ul9Mt7WYux3YrVK6MyLTTk51c16qG58TQgGO2q8v.webp'},
        'Chizi':{'price': 6000, 'image':'https://api.lesailes.uz/storage/products/2022/02/16/dAYUUycesFJlcoSf3lymRFBusRAAziZHyuY93Puv.webp'}
    }
}